version: "3.8"

services:
  db:
    image: postgres
    container_name: database-postgres
    environment:
      POSTGRES_DB: IE3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
