-- Pessoas
INSERT INTO PESSOA (NOME) VALUES ('Marina Acosta');
INSERT INTO PESSOA (NOME) VALUES ('Nicholas Navarro');
INSERT INTO PESSOA (NOME) VALUES ('Gustavo Teixeira');
INSERT INTO PESSOA (NOME) VALUES ('Rafael Vaccaro');
INSERT INTO PESSOA (NOME) VALUES ('Gabriel Mr Velloso');

-- Perfis
INSERT INTO PERFIL (TIPO) VALUES ('GERENTE');
INSERT INTO PERFIL (TIPO) VALUES ('DEV');
INSERT INTO PERFIL (TIPO) VALUES ('QA');
INSERT INTO PERFIL (TIPO) VALUES ('SECURITY');

-- PerfilPessoa

INSERT INTO PERFIL_PESSOA (PESSOA_ID, PERFIL_ID)
VALUES (1, 1);
INSERT INTO PERFIL_PESSOA (PESSOA_ID, PERFIL_ID)
VALUES (2, 2);
INSERT INTO PERFIL_PESSOA (PESSOA_ID, PERFIL_ID)
VALUES (3, 3);
INSERT INTO PERFIL_PESSOA (PESSOA_ID, PERFIL_ID)
VALUES (4, 4);
INSERT INTO PERFIL_PESSOA (PESSOA_ID, PERFIL_ID)
VALUES (5, 3);

-- Projetos
INSERT INTO PROJETO (NOME, DESCRICAO, DATA_INICIO, DATA_FIM, IS_ACTIVE) 
VALUES ('Projeto Alpha', 'Sistema de gestão corporativa', '2025-01-10', '2025-12-30', false);

INSERT INTO PROJETO (NOME, DESCRICAO, DATA_INICIO, DATA_FIM, IS_ACTIVE) 
VALUES ('Projeto Beta', 'Aplicativo mobile de delivery', '2025-02-01', '2025-08-15',false);

INSERT INTO PROJETO (NOME, DESCRICAO, DATA_INICIO, DATA_FIM, IS_ACTIVE) 
VALUES ('Projeto Omega', 'Plataforma de gerenciamento financeiro', '2025-03-01', '2025-09-20', false);

INSERT INTO PROJETO (NOME, DESCRICAO, DATA_INICIO, DATA_FIM, IS_ACTIVE) 
VALUES ('Projeto Delta', 'Sistema de controle de estoque', '2025-01-15', '2025-07-10', false);

INSERT INTO PROJETO (NOME, DESCRICAO, DATA_INICIO, DATA_FIM, IS_ACTIVE) 
VALUES ('Projeto Sigma', 'Plataforma de e-learning', '2025-04-01', '2025-12-15', false);

-- Contratos
INSERT INTO CONTRATO (PERFIL_PESSOA_ID, DATA_INICIO, DATA_FIM, HORAS_SEMANAIS, SALARIO_HORA)
VALUES (1, '2025-01-01', '2025-12-31', 40, 70.0);

INSERT INTO CONTRATO (PERFIL_PESSOA_ID, DATA_INICIO, DATA_FIM, HORAS_SEMANAIS, SALARIO_HORA)
VALUES (2, '2025-02-01', '2025-12-31', 35, 45.0);

INSERT INTO CONTRATO (PERFIL_PESSOA_ID, DATA_INICIO, DATA_FIM, HORAS_SEMANAIS, SALARIO_HORA)
VALUES (3, '2025-01-15', '2025-11-30', 30, 40.0);

INSERT INTO CONTRATO (PERFIL_PESSOA_ID, DATA_INICIO, DATA_FIM, HORAS_SEMANAIS, SALARIO_HORA)
VALUES (4, '2025-03-01', '2025-09-30', 20, 60.0);

INSERT INTO CONTRATO (PERFIL_PESSOA_ID, DATA_INICIO, DATA_FIM, HORAS_SEMANAIS, SALARIO_HORA)
VALUES (5, '2025-02-10', '2025-08-31', 25, 35.0);

-- Alocações
INSERT INTO ALOCACAO (PERFIL_PESSOA_ID, PROJETO_ID, QUANTIDADE_HORAS)
VALUES (1, 1, 120);

INSERT INTO ALOCACAO (PERFIL_PESSOA_ID, PROJETO_ID, QUANTIDADE_HORAS)
VALUES (2, 1, 90);

INSERT INTO ALOCACAO (PERFIL_PESSOA_ID, PROJETO_ID, QUANTIDADE_HORAS)
VALUES (3, 1, 80);

INSERT INTO ALOCACAO (PERFIL_PESSOA_ID, PROJETO_ID, QUANTIDADE_HORAS)
VALUES (4, 4, 60);

INSERT INTO ALOCACAO (PERFIL_PESSOA_ID, PROJETO_ID, QUANTIDADE_HORAS)
VALUES (5, 5, 100);
