INSERT INTO PERFIL (TIPO) VALUES ('GERENTE');
INSERT INTO PERFIL (TIPO) VALUES ('DEV');
INSERT INTO PERFIL (TIPO) VALUES ('QA');
INSERT INTO PERFIL (TIPO) VALUES ('SECURITY');

INSERT INTO PESSOA (NOME) VALUES ('Gustavo Teixeira');
INSERT INTO PESSOA (NOME) VALUES ('Nicholas Navarro');
INSERT INTO PESSOA (NOME) VALUES ('Bernardo Fioreze');


INSERT INTO PERFIL_PESSOA (PESSOA_ID, PERFIL_ID)
VALUES (1, 1);

INSERT INTO PERFIL_PESSOA (PESSOA_ID, PERFIL_ID)
VALUES (2, 2);

INSERT INTO PERFIL_PESSOA (PESSOA_ID, PERFIL_ID)
VALUES (3, 3);


INSERT INTO PROJETO (NOME, DESCRICAO, DATA_INICIO, DATA_FIM) 
VALUES ('Projeto de Teste', 'Descrição do projeto de teste', '2025-09-24', '2025-10-30');

INSERT INTO CONTRATO (PERFIL_PESSOA_ID, DATA_INICIO, DATA_FIM, HORAS_SEMANAIS, SALARIO_HORA)
VALUES (1, '2025-09-24', '2025-10-30', 40, 70.0);