INSERT INTO PERFIL (TIPO) VALUES ('GERENTE');
INSERT INTO PERFIL (TIPO) VALUES ('DEV');
INSERT INTO PERFIL (TIPO) VALUES ('QA');
INSERT INTO PERFIL (TIPO) VALUES ('SECURITY');

INSERT INTO PESSOA (NOME) VALUES ('Gustavo Teixeira');
