INSERT INTO PERFIL (TIPO) VALUES ('GERENTE');
INSERT INTO PERFIL (TIPO) VALUES ('DEV');
INSERT INTO PERFIL (TIPO) VALUES ('QA');
INSERT INTO PERFIL (TIPO) VALUES ('SECURITY');

INSERT INTO PESSOA (NOME) VALUES ('Gustavo Teixeira');

INSERT INTO PERFIL_PESSOA (PESSOA_ID, PERFIL_ID)
VALUES (1, 1);
